#!/usr/bin/env bash

#  ----------------------------------------------------------------------------
#  "THE NXT-WARE LICENSE" NXT: 13570469120032392161 (Revision: 25519)
#  j0b <gemeni@gmail.com> wrote this file. As long as you retain this notice you
#  can do whatever you want with this stuff. IF you think this stuff is worth it, 
#  you can send me NXT, my public key is above.
#  ----------------------------------------------------------------------------


# NXT-Client configuration
source "/etc/nxt/nxt.conf"

if [[ -z "$pidfile" ]] || [[ -z "$nxtuser" ]] || [[ -z "$javapath" ]] 
   [[ -z "$stdaemon" ]] || [[ -z "$client_args" ]] || [[ -z "$nicelevel" ]]
   [[ -z "$memlow" ]] || [[ -z "$memhigh" ]]; then

    echo "Missing configuration in nxt.conf.";
    exit 0
fi

function start {

    # Make sure that pidfile exists and is owned by nxtuser
    touch $pidfile && chown $nxtuser:$nxtuser $pidfile
    $stdaemon --start --chdir "$nxtroot" --background --chuid "$nxtuser" --nicelevel $nicelevel \
    --quiet --pidfile "$pidfile" --make-pidfile --exec "$javapath" -- $client_args 2>&1
    # Fix "waitpid". Currently waitpid can not monitor non child processes
    sleep 4
    status

}


function stop {

   sync
   "$javapath" $client_args --stop 2>&1
   # Fix "waitpid". Currently waitpid can not monitor non child processes
   sleep 4
   status

}

function status {

    $stdaemon -T --pidfile "$pidfile" && echo "NXT-Client is started." \
    || echo "NXT-Client is stopped."

}
   

case "$1" in

    start)
        start

    ;;
    stop)
        stop

    ;;
    restart)
        stop
        start

    ;;
    status)
        status

    ;;
    *)

    N=/etc/init.d/${0##*/}
    echo "Usage: $N {start|stop|status}" >&2
    exit 1
    ;;
esac

exit 0
